# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83fc6ad523c20eccb0c47d7d7776dd699feda7d92da90c8c9aacf5ee9b0b9b187b7e97ec031d7f26f3cc19250b0bd4ccaaa7d373b2d0a2fa88842a3019a0697f

test:
  secret_key_base: b9885b2d02dea585cafab6378ff8cbf0b63f2e48e401a1ee5b0cc8854a25935984416c40a4c081a9d22b8394097bc4cebba5537561c3c3695bfb680841d2a201

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
